<?php
// generate_sql_dump.php
// Usage:
// php generate_sql_dump.php --env="C:\path\to\.env" --output="C:\Users\Edu Juanda Pratama\Downloads\dump.sql"
// or provide DB params:
// php generate_sql_dump.php --host=127.0.0.1 --port=3306 --user=root --pass=secret --db=dbname --output="C:\Users\...\dump.sql"

ini_set('memory_limit','-1');
set_time_limit(0);

$options = getopt("", ["env::","host::","port::","user::","pass::","db::","output::","batch::","help::"]);
if (isset($options['help'])) {
    echo "Usage: php generate_sql_dump.php [--env=path_to_.env] [--host=] [--port=] [--user=] [--pass=] [--db=] [--output=] [--batch=200]\n";
    exit;
}

function parseEnvFile($path) {
    if (!file_exists($path)) return [];
    $lines = file($path, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
    $data = [];
    foreach ($lines as $line) {
        $line = trim($line);
        if ($line === '' || $line[0] === '#') continue;
        if (strpos($line, '=') === false) continue;
        list($name,$value) = explode('=', $line, 2);
        $name = trim($name);
        $value = trim($value);
        if ((substr($value,0,1) === '"' && substr($value,-1) === '"') || (substr($value,0,1) === "'" && substr($value,-1) === "'")) {
            $value = substr($value,1,-1);
        }
        $data[$name] = $value;
    }
    return $data;
}

// Try .env if provided or search up to 6 parent dirs
$envData = [];
if (isset($options['env']) && file_exists($options['env'])) {
    $envData = parseEnvFile($options['env']);
} else {
    $dir = getcwd();
    for ($i=0;$i<6;$i++) {
        $candidate = $dir . DIRECTORY_SEPARATOR . '.env';
        if (file_exists($candidate)) { $envData = parseEnvFile($candidate); break; }
        $parent = dirname($dir);
        if ($parent === $dir) break;
        $dir = $parent;
    }
}

$dbHost = $options['host'] ?? $envData['DB_HOST'] ?? '127.0.0.1';
$dbPort = $options['port'] ?? $envData['DB_PORT'] ?? 3306;
$dbUser = $options['user'] ?? ($envData['DB_USERNAME'] ?? ($envData['DB_USER'] ?? 'root'));
$dbPass = $options['pass'] ?? ($envData['DB_PASSWORD'] ?? ($envData['DB_PASS'] ?? ''));
$dbName = $options['db'] ?? ($envData['DB_DATABASE'] ?? null);

if (empty($dbName)) {
    fwrite(STDERR, "ERROR: Database name is required (use --db or set DB_DATABASE in .env)\n");
    exit(1);
}

$output = $options['output'] ?? ('C:\\Users\\Edu Juanda Pratama\\Downloads\\dump_' . preg_replace('/[^0-9A-Za-z_]/','_', $dbName) . '_' . date('Ymd_His') . '.sql');
$batch = max(1, intval($options['batch'] ?? 200));

$dsn = "mysql:host={$dbHost};port={$dbPort};dbname={$dbName};charset=utf8mb4";
try {
    $pdo = new PDO($dsn, $dbUser, $dbPass, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci"
    ]);
} catch (Exception $e) {
    fwrite(STDERR, "Connection failed: " . $e->getMessage() . PHP_EOL);
    exit(1);
}

$fh = fopen($output, 'w');
if (!$fh) { fwrite(STDERR, "Cannot open output file: $output\n"); exit(1); }

fwrite($fh, "-- SQL dump generated by generate_sql_dump.php\n");
fwrite($fh, "-- Host: {$dbHost}    Database: {$dbName}\n");
fwrite($fh, "-- Generation time: " . date('Y-m-d H:i:s') . "\n\n");
fwrite($fh, "SET FOREIGN_KEY_CHECKS=0;\n");
fwrite($fh, "SET NAMES utf8mb4;\n\n");

// get tables
$tables = [];
try {
    $stmt = $pdo->query("SHOW FULL TABLES WHERE Table_type = 'BASE TABLE'");
    $rows = $stmt->fetchAll(PDO::FETCH_NUM);
    if (!$rows) {
        $stmt = $pdo->query("SHOW TABLES");
        $rows = $stmt->fetchAll(PDO::FETCH_NUM);
    }
    foreach ($rows as $r) $tables[] = $r[0];
} catch (Exception $e) {
    fwrite(STDERR, "Failed to list tables: ". $e->getMessage() ."\n");
    exit(1);
}

foreach ($tables as $table) {
    fwrite($fh, "\n-- ----------------------------\n");
    fwrite($fh, "-- Table structure for `{$table}`\n");
    fwrite($fh, "-- ----------------------------\n\n");
    fwrite($fh, "DROP TABLE IF EXISTS `{$table}`;\n");

    $row = $pdo->query("SHOW CREATE TABLE `{$table}`")->fetch(PDO::FETCH_NUM);
    $createStmt = $row[1] ?? $row[0] ?? '';
    $createStmt = rtrim($createStmt, ';') . ";\n\n";
    fwrite($fh, $createStmt);

    fwrite($fh, "-- ----------------------------\n");
    fwrite($fh, "-- Data for table `{$table}`\n");
    fwrite($fh, "-- ----------------------------\n\n");

    // get column names
    $colRes = $pdo->query("SHOW COLUMNS FROM `{$table}`")->fetchAll(PDO::FETCH_ASSOC);
    $columns = array_map(function($c){ return $c['Field']; }, $colRes);
    if (count($columns) === 0) continue;
    $colsBackticked = array_map(function($c){ return "`$c`"; }, $columns);
    $colList = implode(',', $colsBackticked);

    $stmt = $pdo->query("SELECT * FROM `{$table}`");
    $valuesBatch = [];
    while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
        $vals = [];
        foreach ($columns as $colName) {
            $v = $row[$colName];
            if ($v === null) $vals[] = "NULL";
            else $vals[] = $pdo->quote($v);
        }
        $valuesBatch[] = '(' . implode(',', $vals) . ')';
        if (count($valuesBatch) >= $batch) {
            fwrite($fh, "INSERT INTO `{$table}` ({$colList}) VALUES\n" . implode(",\n", $valuesBatch) . ";\n");
            $valuesBatch = [];
        }
    }
    if (count($valuesBatch) > 0) {
        fwrite($fh, "INSERT INTO `{$table}` ({$colList}) VALUES\n" . implode(",\n", $valuesBatch) . ";\n");
    }
    fwrite($fh, "\n");
}

fwrite($fh, "SET FOREIGN_KEY_CHECKS=1;\n");
fclose($fh);

echo "Selesai — dump disimpan di: $output\n";
